[phases.setup]
nixPkgs = ["python311", "file", "tesseract", "poppler_utils"]

[phases.install]
cmds = [
    # All these commands run in a single shell session
    "python3.11 -m venv .venv && " # Create venv
    "source .venv/bin/activate && " # Activate venv
    "pip install --upgrade pip && " # Upgrade pip within the venv
    "pip install -r requirements.txt" # Install dependencies into the venv
]

[start]
# Ensure the virtual environment is activated when your application starts
cmd = "source .venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"