[phases.setup]
nixPkgs = ["python311", "file", "tesseract", "poppler_utils"]

[phases.install]
# All commands are now in a single string, within one array element
cmds = ["python3.11 -m venv .venv && source .venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"]

[start]
cmd = "source .venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"