[phases.setup]
nixPkgs = ["python311", "file", "tesseract", "poppler_utils"]

[phases.install]
cmds = ["python3.11 -m venv .venv && source .venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"]

[start]
cmd = "./start.sh" # Point directly to your new wrapper script