[phases.setup]
nixPkgs = ["python311", "file", "tesseract", "poppler_utils"]

[phases.install]
cmds = ["python3.11 -m venv .venv && source .venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"]

[start]
# Explicitly set PYTHONPATH to the current directory (which is /app)
cmd = "export PYTHONPATH=. && LIBMAGIC_DIR=$(find /nix/store -type f -name 'libmagic.so*' 2>/dev/null | head -n 1 | xargs dirname) && export LD_LIBRARY_PATH=\"$LIBMAGIC_DIR:$LD_LIBRARY_PATH\" && source /root/.nix-profile/etc/profile.d/nix.sh && source .venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"