[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "file", "tesseract", "poppler_utils"]

[phases.install] 
cmds = ["python -m pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"