[phases.setup]
nixPkgs = ["python311", "file", "tesseract", "poppler_utils"]
# No need for python311Packages.pip here, as we'll use pip from the venv

[phases.install]
# Explicitly create and activate a virtual environment, then install dependencies
cmds = [
    "python3.11 -m venv .venv",       # 1. Create a virtual environment named .venv
    "source .venv/bin/activate",      # 2. Activate the virtual environment
    "pip install --upgrade pip",      # 3. (Optional but good practice) Upgrade pip within the venv
    "pip install -r requirements.txt" # 4. Install your project's dependencies into the venv
]

[start]
# Ensure the virtual environment is activated when your application starts
cmd = "source .venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"