[phases.setup]
# Ensure 'file' is present, which contains libmagic
nixPkgs = ["python311", "file", "tesseract", "poppler_utils"]

[phases.install]
cmds = ["python3.11 -m venv .venv && source .venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"]

[start]
# Explicitly source the Nix profile's environment setup before running your app
# This ensures LD_LIBRARY_PATH and other env vars are correctly set for C libraries
cmd = "source /root/.nix-profile/etc/profile.d/nix.sh && source .venv/bin/activate && uvicorn main:app --host 0.0.0.0 --port $PORT"