[phases.setup]
nixPkgs = ["python311", "file", "tesseract", "poppler_utils"] \

[phases.install]

cmds = [
    "python3.11 -m ensurepip --default-pip", # Ensures pip is available for python3.11
    "python3.11 -m pip install --upgrade pip setuptools wheel", # Upgrades pip and related tools
    "python3.11 -m pip install -r requirements.txt" # Installs your project's dependencies
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"